server:
  port: ${vcap.application.port:8080}
---
  
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration    
    
  security.ldap:
    active: false
    url: ldap://10.100.0.0:389
    authentication: simple
    baseDN: OU=userldap,DC=gob,DC=com,DC=pe
    admin: gitlab@test.com.pe
    password: password
    
  production:
    active: false
    
  security.jwt:
    tokenExpirationTime: 240 # Number of minutes
    refreshTokenExpTime: 1440 # Minutes
    tokenIssuer: http://gmd.com.pe
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus  
  
  urlpasswordreset:
    ipfrontend: http://localhost:4200/reset/validatePassword
  
  mail:
    sender: lmgomez.saavedra@gmail.com
    fromIP: 192.168.1.45
    host: 192.168.0.10
    username: lgomezs
    password: H4ZG9:iQ
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false
                  
multipart.maxFileSize: 20MB
multipart.maxRequestSize: 20MB 